### ISSUE TITLE
BackgroundJobs

### ISSUE THREAD

**Issue by Diaskhan** [caifl/bpmtk#1]
1.For background jobs better to use 
https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/multi-container-microservice-net-applications/background-tasks-with-ihostedservice

2.Could U provide some Demo for tests ?

**Comment by caifl** [comment]
Thanks !
I will try it later.
I am working on WebAPI and WebClient(Vue).

**Comment by Diaskhan** [comment]
I have some ideas how implement many thigs ! 

For example.
For procces designer better use draw.io (mxgraph library).
For dal layer ive working on entity designer that could make migrations online ! 
If u need some help ! I could help u ! 

Ihave understanding of execution tokens !

**Comment by Diaskhan** [comment]
Could u provide minimal example how to use engine ?  With simple business process ?

**Comment by caifl** [comment]
Please check out the following files: 
1. UnitTests:
https://github.com/caifl/bpmtk/blob/master/src/Bpmtk.Engine.Tests/BpmtkTestCase.cs

Fork-Join TestCase:
https://github.com/caifl/bpmtk/blob/master/src/Bpmtk.Engine.Tests/Bpmn/Gateway/NestedForkJoinTestCase.cs

2. Web API Project:
https://github.com/caifl/bpmtk/blob/master/src/Bpmtk.Engine.WebApi/ProcessEngineExtensions.cs

**Comment by Diaskhan** [comment]
I'm closing the issue.
If have question. 
Will write email!
