### ISSUE TITLE
Ui prototype ? (Element UI)

### ISSUE THREAD

**Issue by Diaskhan** [caifl/bpmtk#10]
Could draw some screen prototype to make UI ?

![image](https://user-images.githubusercontent.com/15046677/57314573-bd8d9280-7113-11e9-9754-e5366e62bb02.png)

I see 4 possible windows !
1.Human task manager.
2.Process Repository.
3.Deployment manager!
4.Process monitoring!

**Comment by Diaskhan** [comment]
U could use Sketch Editor
http://docs.icons8.com/release-notes/

And Sketch template for them !
https://element.eleme.io/#/en-US/resource

**Comment by Diaskhan** [comment]
![image](https://user-images.githubusercontent.com/15046677/57315457-6be60780-7115-11e9-8969-71e63d4dc713.png)

**Comment by caifl** [comment]
That is a nice prototype tool.
I am new to github, how could i post pictures, thanks.

**Comment by Diaskhan** [comment]
Just copy from buffer. And paste in input textbox !

**Comment by Diaskhan** [comment]
Any updates ? 
When is shetcg gonna be ready ?

**Comment by Diaskhan** [comment]
Maybe U make prototype ? and I could start make Adm console for U ?

**Comment by Diaskhan** [comment]
Do u know whats wrong with swager try to query.
But getting this mistake !
![image](https://user-images.githubusercontent.com/15046677/57569261-1dd24c00-7414-11e9-8e36-a7342338ef04.png)

**Comment by Diaskhan** [comment]
Changed to **httpost** and it works! could u test all api ?
