### ISSUE TITLE
Swagger Improvemnt

### ISSUE THREAD

**Issue by Diaskhan** [caifl/bpmtk#11]
Best is to make all parametres in camel.

```
services.AddSwaggerGen(c =>
            {
                c.DescribeAllParametersInCamelCase();
            });
```

I finded that using swagger js he dont apply parameters.

Better to camelcased all and everthing be fine !

**Comment by Diaskhan** [comment]
![image](https://user-images.githubusercontent.com/15046677/57413368-b189f980-7215-11e9-89df-d0195c810a56.png)

**Comment by caifl** [comment]
I have made changes.

Then we can start to create Modeler by use IPackageManager API, which can add/update model, and produce model version history(HistoricModel).

The "Package" can contains "PackageItem", such as  forms, business objects, views etc in Process Design-Time.

**Comment by Diaskhan** [comment]
Its litlle bit earlier to talk about packaging in my opinion. Could u show some link or show conception where u re borrowed idea ? 
In my primary job. We work with bpm online. https://www.bpmonline.com/ I could show u have there package systems works!

**Comment by caifl** [comment]
A package represents the smallest deployment-unit in design-time,
which should contains one bpmn model(may be one or more processes),
and also other resources.  such as forms, views, business objects(entities meta-data). configration.(optional)

After a package deployed,  system will create a module or small app.

1. Joget workflow:
https://www.joget.com/joget-workflow.html

2. Oracle BPM Suite:
https://docs.oracle.com/middleware/1221/bpm/bp-composer-user/GUID-DB167B67-9B6C-4017-937F-82B884C9AC2C.htm#BPMCU352

![image](https://user-images.githubusercontent.com/2098298/57441714-13ca1500-727d-11e9-919a-114db864a159.png)

**Comment by caifl** [comment]
So, the next step,  we need to create Process Modeler to design sample process model, 
then evaluate workflow-patterns. 
http://www.workflowpatterns.com/

**Comment by Diaskhan** [comment]
U wanne make true bpm concept! 
When in Each step shows possible fields for each human task !
Like that !
![image](https://user-images.githubusercontent.com/15046677/57443685-72d55d00-7270-11e9-9aca-beb8d7e44fd0.png)


I agree the fields and details of business object is linked to Business Process!

But have another conceptions!
Where field of forms may be many, many many 
![image](https://user-images.githubusercontent.com/15046677/57443830-baf47f80-7270-11e9-9052-82cadf6e9182.png)

In second case Dal Layer Must divided from true Bpm Concept!
1.True bpm process (when fields hardly binded to process)
2.Process with weak link  (when Card weak binded to process)


**Conclusion.
 I know about Oracle BPM. But when is trully bpm forms, 
The interface of conception is not so user friendly !**

If We wanna cover ECM,CRM,BPM conception there must be Choice between this conceptions!

**Comment by Diaskhan** [comment]
What about Process Modeler do U want to use BPMN .io designer with trademark ?

**Comment by Diaskhan** [comment]
Right now working on EntityDesigner that could create entity and apply migration  in runtime.
When finish that work could show U!
![image](https://user-images.githubusercontent.com/15046677/57445401-196f2d00-7274-11e9-8159-1d051f7139ec.png)

**Comment by caifl** [comment]
I think the BPM Process only contains control data and related data when they need. but some times, we should to make some demonstration without coding/compilation.

1. we do not need to consider very very complex business model.  

2. with restful api/json,  we can seperate business objects persistence layer from BPM.

**Comment by Diaskhan** [comment]
In bpm online there Added Workflow element that could read data from Business Objects!
And save it to variable, or use contitional gateway from readed data !
![image](https://user-images.githubusercontent.com/15046677/57472898-65d85e00-72b0-11e9-9c60-1960354cc978.png)
Very elegant solution improving bpmn behaviours!

https://academy.bpmonline.com/documents/technic-bpms/7-13/read-data-process-element

**Comment by caifl** [comment]
I have learned  bpmn-js last year,  and made a simple modeler with angularjs.

**Comment by Diaskhan** [comment]
Could U show me ? What about Vuejs ? vue better at all.

**Comment by caifl** [comment]
there are many approach to load/link business objects.  

1. forms-ui;

2. scriptTask/serviceTask;

3. activityEvent(such as ready, start, end), to load data. (in activiti has event listener, 
and in BPMTK  we can has two ways,      event listener / inline scripts   )

https://github.com/caifl/bpmtk/blob/master/src/Bpmtk.Engine/Events/CompositeProcessEventListener.cs#L89

**Comment by Diaskhan** [comment]
> I have learned bpmn-js last year, and made a simple modeler with angularjs.

Could U show ure bpmnjs modeler ?

**Comment by caifl** [comment]
![image](https://user-images.githubusercontent.com/2098298/57476660-a7293780-72c9-11e9-9dd9-c480f68852cd.png)

**Comment by caifl** [comment]
I just made custom properties-panel with angularjs.  because of bpmn-js 's properties-panel code is hard to read,  extend.

**Comment by Diaskhan** [comment]
What about Sketch ? i'm wating for them. need to make ui. Could make it on elementui and vuejs ?

**Comment by Diaskhan** [comment]
By the way. need to think about i18n! 
We could cover English,Chinese and Russian languages!

U re from China ?

**Comment by caifl** [comment]
I just made custom properties-panel with angularjs.  because of bpmn-js 's properties-panel code is hard to read,  extend.

**Comment by caifl** [comment]
Yes, chinese, 

I am re-writing it with vuejs  and element-ui.
