### ISSUE TITLE
Not compiling

### ISSUE THREAD

**Issue by Diaskhan** [caifl/bpmtk#2]
Hie i tried to compile the solution!
But it trhrows errors
[error log.txt](https://github.com/caifl/bpmtk/files/3128727/error.log.txt)

Could U help me to build solution ?
![image](https://user-images.githubusercontent.com/15046677/56918572-30798680-6ae0-11e9-9f4b-8ed0bd2cd883.png)

**Comment by caifl** [comment]
Unload the "Bpmtk.Engine.Hibernate" project, try again.

**Comment by Diaskhan** [comment]
![image](https://user-images.githubusercontent.com/15046677/56919584-cc0bf680-6ae2-11e9-9936-e71f0a3a999d.png)

**Comment by Diaskhan** [comment]
Still not compiling...

**Comment by caifl** [comment]
Sorry,
Unload the "ConsoleApp" project, too.
