### ISSUE TITLE
Plans Roadmaps ?

### ISSUE THREAD

**Issue by Diaskhan** [caifl/bpmtk#3]
Could describe some plans or roadmap ?
What next could be done ?
I guesse some docs needed.

Its Activity Port???

**Comment by caifl** [comment]
I am so sorry,  my english language is so poor. 
Do you have some suggestions, or can do it with me together.
I think to take some good ideas from Activiti and JBPM, and code it with .NET CORE/CSharp style.

The first step to do is that I will write the UnitTests for Process Engine, to cover all the APIs,  the interfaces 'IxxxManager'.  (You can check out the Project 'Bpmtk.Engine.Tests')

Step 2:   Complete the webApi,  ('Bpmtk.Engine.WebApi');

Step 3:   BPMN 2.0 Modeler based on BPMN-JS;

Step 4:  VueJs WebApp. (Administration,  Process Monitor,   Task List)

Step 5:  Embbed H5 Form Editor. (Simple,  mybe automation in runtime).

Step 6:  Advanced Form Editor for Enterprise Process Enabled Applications.

Thanks.

**Comment by Diaskhan** [comment]
In my vision,
All stuff is needed.
2.Yes.
3.Its possible, but logo of bpmn.io makes me go insane))
4.Yes, I have seen many UI libs, the possible options 
https://github.com/bootstrap-vue/bootstrap-vue
https://github.com/ElemeFE/element
There are mature and solid
5. Maybe Form.Io posssible option! Have integrations with vue!
6. Very ambicious for begging!


99.Its seems to me for good start is need to provide simplicity of installations.
And realize just simple tutorial to make human task, parallel gateways,exclusive gateway. Provide screenshots!
After all many users come to the repository and many people wil start dicsusing and improving engine!

Provide some checklist what is implemented, and what plans to implement BPMN 2.0.
Many Commercial Bpmn engine doesnt fully implemented BPMN 2.0 because is very hard!
The all says "Bpmn 2.0" but its marketing!

**Comment by Diaskhan** [comment]
The solution must be launcahble, downloaded and all works fine!

**Comment by caifl** [comment]
The code have been changed many, because of I seperated the models,bpmn2 elements, node behaviors from mini core runtime to make the engine more extensiblly.  

For BPMN 2.0, I will implement it as more as possible, and accordings to OMG Specification.  that's why I start this project.

**Comment by caifl** [comment]
UserTask, ParallalGateway have been implemented, there is an image in the resources folder for 'fork-join' bpmn 2.0 sample file.

**Comment by Diaskhan** [comment]
Maybe i Will start to make some UI ?. Need minimum viable product. deploy and laung engine.

**Comment by Diaskhan** [comment]
I ve started a topic. Maybe we shall discucc this in https://github.com/caifl/bpmtk/issues/7 ??
