### ISSUE TITLE
Migration 

### ISSUE THREAD

**Issue by Diaskhan** [caifl/bpmtk#5]
What needs to be done to Install database ?
From Poject need to apply migrations ?
What version of Mysql need to Use ?

**Comment by caifl** [comment]
I test it with Mysql v5.7. 

1.  Create database schema, and change Mysql conntion string:
     Edit the cs file:       /ConsoleApp/Xyz.cs  

2. Open the foler 'ConsoleApp' with Windows PowerShell.

3.  Execute cmd:   dotnet ef migrations remove   
     remove current migrations.

4. Execute cmd:   dotnet ef database update
    create tables/relationships.

**Comment by Diaskhan** [comment]
Thans i will try!

**Comment by Diaskhan** [comment]
For Web api projests actually need to define bpmtk3
   services.AddDbContext<BpmDbContext>(builder =>
            {
                builder.UseLoggerFactory(LoggerFactory);
                builder.UseLazyLoadingProxies(true);
                builder.UseMySql("server=localhost;uid=root;pwd=123456;database=bpmtk3");
            });
