### ISSUE TITLE
Minimal tutorial

### ISSUE THREAD

**Issue by Diaskhan** [caifl/bpmtk#7]
Let start from begining!

1.Need to guide to install engine.
.........
2.Deploy simple bpmn model for process with UI!
How deploy model to system ? Api
3.Launch simple process.
How to launch process ?
4.Parallel gateway model.

5.Simple Tasklist
Need to create simple ui to execute human tasks.

**Comment by caifl** [comment]
I have write a simple demo in  'ConsoleApp', 
Please check out the file:
https://github.com/caifl/bpmtk/blob/master/src/ConsoleApp/Program.cs

**Comment by caifl** [comment]
The UI includes  BPMN Modeler, Process Monitor, Tasklist handler are in development.
