### ISSUE TITLE
Ui Dev console

### ISSUE THREAD

**Issue by Diaskhan** [caifl/bpmtk#8]
By the way if u using swagger.
It possible to fetch data from api 
https://github.com/swagger-api/swagger-js/blob/master/README.md

To make ajax calls and retrive data !

**Comment by caifl** [comment]
That's a good idea, i will try it later, thanks.

Then i will make some sample project to describ how to start coding too.

**Comment by caifl** [comment]
my e-mail address is:   fl.cai@msn.com
if you have any suggestions, please contact me.
thanks.

**Comment by Diaskhan** [comment]
There must be Treeview of Procces!
And when we selecting process Displays. Additional infomation of process.
1.Diagram where we could view our process
2.Proccess name,last changed, description,
Table with versions of processes. 
3.If we want Create or edit Process must open new window, where diagrams is editing!

The treeview component have expiritnce with  Element Ui  treeview
https://codesandbox.io/s/m31859x86p


![image](https://user-images.githubusercontent.com/15046677/57024458-76f0f180-6c56-11e9-865d-c2997cf3a444.png)

![image](https://user-images.githubusercontent.com/15046677/57024724-1ada9d00-6c57-11e9-845b-6e02fd69bd48.png)

**Comment by caifl** [comment]
Yes,  Very nice, thanks.
