### ISSUE TITLE
Mysql dump

### ISSUE THREAD

**Issue by Diaskhan** [caifl/bpmtk#9]
Could u add mysql dump with real data? 

I wanna try to make web app !

**Comment by caifl** [comment]
I meet a problem,  mysql workbench prompt "mysqldump version mismatch", so i can't export data now.
I will upload the scripts, when i can export it.

**Comment by Diaskhan** [comment]
https://stackoverflow.com/questions/15644697/mysqlworkbench-giving-version-error-on-exporting-database

**Comment by caifl** [comment]
Thanks, and i upload the sql scripts for mysql with sample data.
https://github.com/caifl/bpmtk/blob/master/db/mysql/bpmtk_init_with_data.sql

**Comment by caifl** [comment]
Now the engine can supports StartEvent/EndEvent, UserTask, Parallel/Exclusive Gateway, SubProcess,
and  MultiInstance Loop Activity(not all features verified)

**Comment by Diaskhan** [comment]
Dump is almost empty!
Hardly make ui with no data!

**Comment by Diaskhan** [comment]
Add Checklist in issue what already supported ! Need for DOCS!

**Comment by Diaskhan** [comment]
Later, when have time need to create many demos for demo examples!

**Comment by Diaskhan** [comment]
By the way How decided to make EventsStartPoint, SendMessage,SendEvent ?

**Comment by caifl** [comment]
The dump scripts contains 10 processInstances & 9 processDefinitions(bpmn models). 
https://github.com/caifl/bpmtk/blob/master/db/mysql/bpmtk_init_with_data.sql#L442

**Comment by caifl** [comment]
I am finding APIs documentation generator for C#, to create documents.
The message startEvent will be supported soon.
But the timer startEvent has some questions: such as ScheduledJob Management, time format standards.

**Comment by caifl** [comment]
I will add userTask partipants (performer in BPMN 2.0), data associations supports  implementation.

**Comment by Diaskhan** [comment]
Need good documentation ! 
Similar to https://github.com/danielgerlag/workflow-core

I have searched many times to find ure repo !

**Comment by Diaskhan** [comment]
Currently working right now on entity designer ! That creates entity and migrate database ! Later when gonna be done. Show u ! Dal layer is need for bpmn platform !
